# Generated by Django 5.1.3 on 2024-11-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
